<?php

use Illuminate\Database\Seeder;
use \App\Recipe;

class RecipesTableSeeder extends Seeder
{

    public function run()
    {
         $data = array(
          array("id"=>1,"created_at"=>"30/06/2015 17:58:00","updated_at"=>"30/06/2015 17:58:00","box_type"=>"vegetarian","title"=>"Sweet Chilli and Lime Beef on a Crunchy Fresh Noodle Salad","slug"=>"sweet-chilli-and-lime-beef-on-a-crunchy-fresh-noodle-salad","short_title"=>"null","marketing_description"=>"Here we've used onglet steak which is an extra flavoursome cut of beef that should never be cooked past medium rare. So if you're a fan of well done steak, this one may not be for you. However, if you love rare steak and fancy trying a new cut, please be","calories_kcal"=>401,"protein_grams"=>12,"fat_grams"=>35,"carbs_grams"=>0,"bulletpoint1"=>"","bulletpoint2"=>"","bulletpoint3"=>"","recipe_diet_type_id"=>"meat","season"=>"all","base"=>"noodles","protein_source"=>"beef","preparation_time_minutes"=>35,"shelf_life_days"=>4,"equipment_needed"=>"Appetite","origin_country"=>"Great Britain","recipe_cuisine"=>"asian","in_your_box"=>"","gousto_reference"=>59),
          array("id"=>2,"created_at"=>"30/06/2015 17:58:00","updated_at"=>"30/06/2015 17:58:00","box_type"=>"gourmet","title"=>"Tamil Nadu Prawn Masala","slug"=>"tamil-nadu-prawn-masala","short_title"=>"null","marketing_description"=>"Tamil Nadu is a state on the eastern coast of the southern tip of India. Curry from there is particularly famous and it's easy to see why. This one is brimming with exciting contrasting tastes from ingredients like chilli powder, coriander and fennel seed","calories_kcal"=>524,"protein_grams"=>12,"fat_grams"=>22,"carbs_grams"=>0,"bulletpoint1"=>"Vibrant & Fresh","bulletpoint2"=>"Warming, not spicy","bulletpoint3"=>"Curry From Scratch","recipe_diet_type_id"=>"fish","season"=>"all","base"=>"pasta","protein_source"=>"seafood","preparation_time_minutes"=>40,"shelf_life_days"=>4,"equipment_needed"=>"Appetite","origin_country"=>"Great Britain","recipe_cuisine"=>"italian","in_your_box"=>"king prawns, basmati rice, onion, tomatoes, garlic, ginger, ground tumeric, red chilli powder, ground cumin, fresh coriander, curry leaves, fennel seeds","gousto_reference"=>58),
          array("id"=>3,"created_at"=>"30/06/2015 17:58:00","updated_at"=>"30/06/2015 17:58:00","box_type"=>"vegetarian","title"=>"Umbrian Wild Boar Salami Ragu with Linguine","slug"=>"umbrian-wild-boar-salami-ragu-with-linguine","short_title"=>"null","marketing_description"=>"This delicious pasta dish comes from the Italian region of Umbria. It has a smoky and intense wild boar flavour which combines the earthy garlic, leek and onion flavours, while the chilli flakes add a nice deep aroma. Enjoy within 5-6 days of delivery.","calories_kcal"=>609,"protein_grams"=>17,"fat_grams"=>29,"carbs_grams"=>0,"bulletpoint1"=>"","bulletpoint2"=>"","bulletpoint3"=>"","recipe_diet_type_id"=>"meat","season"=>"all","base"=>"pasta","protein_source"=>"pork","preparation_time_minutes"=>35,"shelf_life_days"=>4,"equipment_needed"=>"Appetite","origin_country"=>"Great Britain","recipe_cuisine"=>"british","in_your_box"=>"","gousto_reference"=>1),
          array("id"=>4,"created_at"=>"30/06/2015 17:58:00","updated_at"=>"30/06/2015 17:58:00","box_type"=>"gourmet","title"=>"Tenderstem and Portobello Mushrooms with Corn Polenta","slug"=>"tenderstem-and-portobello-mushrooms-with-corn-polenta","short_title"=>"null","marketing_description"=>"One for those who like their veggies with a slightly spicy kick. However, those short on time, be warned ' this is a time-consuming dish, but if you're willing to spend a few extra minutes in the kitchen, the fresh corn mash is extraordinary and worth a t","calories_kcal"=>508,"protein_grams"=>28,"fat_grams"=>20,"carbs_grams"=>0,"bulletpoint1"=>"","bulletpoint2"=>"","bulletpoint3"=>"","recipe_diet_type_id"=>"vegetarian","season"=>"all","base"=>"","protein_source"=>"cheese","preparation_time_minutes"=>50,"shelf_life_days"=>4,"equipment_needed"=>"None","origin_country"=>"Great Britain","recipe_cuisine"=>"british","in_your_box"=>"","gousto_reference"=>56),
          array("id"=>5,"created_at"=>"30/06/2015 17:58:00","updated_at"=>"30/06/2015 17:58:00","box_type"=>"vegetarian","title"=>"Fennel Crusted Pork with Italian Butter Beans","slug"=>"fennel-crusted-pork-with-italian-butter-beans","short_title"=>"null","marketing_description"=>"A classic roast with a twist. The pork loin is marinated in rosemary, fennel seeds and chilli flakes then teamed with baked potato wedges and butter beans in tomato sauce. Enjoy within 5-6 days of delivery.","calories_kcal"=>511,"protein_grams"=>11,"fat_grams"=>62,"carbs_grams"=>0,"bulletpoint1"=>"A roast with a twist","bulletpoint2"=>"Low fat & high protein","bulletpoint3"=>"With roast potatoes","recipe_diet_type_id"=>"meat","season"=>"all","base"=>"beans/lentils","protein_source"=>"pork","preparation_time_minutes"=>45,"shelf_life_days"=>4,"equipment_needed"=>"Pestle & Mortar (optional)","origin_country"=>"Great Britain","recipe_cuisine"=>"british","in_your_box"=>"pork tenderloin, potatoes, butter beans, garlic, fennel seeds, medium onion, chilli flakes, fresh rosemary, tomatoes, vegetable stock cube","gousto_reference"=>55),
          array("id"=>6,"created_at"=>"01/07/2015 17:58:00","updated_at"=>"01/07/2015 17:58:00","box_type"=>"gourmet","title"=>"Pork Chilli","slug"=>"pork-chilli","short_title"=>"null","marketing_description"=>"Succulent pork tenderloin and feathery white bean and parsnip mash mingle with feisty cumin seeds and tangy leek in this lighter, less conventional take on a British classic. Welcome to the outer limits of food!","calories_kcal"=>401,"protein_grams"=>12,"fat_grams"=>35,"carbs_grams"=>0,"bulletpoint1"=>"","bulletpoint2"=>"","bulletpoint3"=>"","recipe_diet_type_id"=>"meat","season"=>"all","base"=>"","protein_source"=>"pork","preparation_time_minutes"=>35,"shelf_life_days"=>4,"equipment_needed"=>"Appetite","origin_country"=>"Great Britain","recipe_cuisine"=>"asian","in_your_box"=>"","gousto_reference"=>60),
          array("id"=>7,"created_at"=>"02/07/2015 17:58:00","updated_at"=>"02/07/2015 17:58:00","box_type"=>"vegetarian","title"=>"Courgette Pasta Rags","slug"=>"courgette-pasta-rags","short_title"=>"null","marketing_description"=>"Kick-start the new year with some get-up and go with this lean green vitality machine. Protein-packed chicken and mineral-rich kale are blended into a smooth, nut-free version of pesto; creating the ultimate composition of nutrition and taste","calories_kcal"=>524,"protein_grams"=>12,"fat_grams"=>22,"carbs_grams"=>0,"bulletpoint1"=>"","bulletpoint2"=>"","bulletpoint3"=>"","recipe_diet_type_id"=>"meat","season"=>"all","base"=>"","protein_source"=>"chicken","preparation_time_minutes"=>40,"shelf_life_days"=>4,"equipment_needed"=>"Appetite","origin_country"=>"Great Britain","recipe_cuisine"=>"british","in_your_box"=>"","gousto_reference"=>59),
          array("id"=>8,"created_at"=>"03/07/2015 17:58:00","updated_at"=>"03/07/2015 17:58:00","box_type"=>"vegetarian","title"=>"Homemade Eggs & Beans","slug"=>"homemade-egg-beans","short_title"=>"null","marketing_description"=>"A Goustofied British institution, learn how to make beautifully golden breaded chicken escalopes drizzled in homemade garlic butter and served atop fluffy potato and broccoli mash.","calories_kcal"=>609,"protein_grams"=>17,"fat_grams"=>29,"carbs_grams"=>0,"bulletpoint1"=>"","bulletpoint2"=>"","bulletpoint3"=>"","recipe_diet_type_id"=>"meat","season"=>"all","base"=>"","protein_source"=>"eggs","preparation_time_minutes"=>35,"shelf_life_days"=>3,"equipment_needed"=>"Appetite","origin_country"=>"Great Britain","recipe_cuisine"=>"italian","in_your_box"=>"","gousto_reference"=>2),
          array("id"=>9,"created_at"=>"04/07/2015 17:58:00","updated_at"=>"04/07/2015 17:58:00","box_type"=>"gourmet","title"=>"Grilled Jerusalem Fish","slug"=>"grilled-jerusalem-fish","short_title"=>"null","marketing_description"=>"I love this super healthy fish dish, it contains a punch from zingy ginger, a kick from chili and a salty sweet balance from soy sauce and mirim. A cleansing and restorative meal, great for body and soul.","calories_kcal"=>508,"protein_grams"=>28,"fat_grams"=>20,"carbs_grams"=>0,"bulletpoint1"=>"","bulletpoint2"=>"","bulletpoint3"=>"","recipe_diet_type_id"=>"meat","season"=>"all","base"=>"","protein_source"=>"fish","preparation_time_minutes"=>50,"shelf_life_days"=>4,"equipment_needed"=>"Appetite","origin_country"=>"Great Britain","recipe_cuisine"=>"mediterranean","in_your_box"=>"","gousto_reference"=>57),
          array("id"=>10,"created_at"=>"05/07/2015 17:58:00","updated_at"=>"05/07/2015 17:58:00","box_type"=>"gourmet","title"=>"Pork Katsu Curry","slug"=>"pork-katsu-curry","short_title"=>"null","marketing_description"=>"Comprising all the best bits of the classic American number and none of the mayo, this is a warm & tasty chicken and bulgur salad with just a hint of Scandi influence. A beautifully summery medley of flavours and textures","calories_kcal"=>511,"protein_grams"=>11,"fat_grams"=>62,"carbs_grams"=>0,"bulletpoint1"=>"","bulletpoint2"=>"","bulletpoint3"=>"","recipe_diet_type_id"=>"meat","season"=>"all","base"=>"","protein_source"=>"pork","preparation_time_minutes"=>45,"shelf_life_days"=>4,"equipment_needed"=>"Appetite","origin_country"=>"Great Britain","recipe_cuisine"=>"mexican","in_your_box"=>"","gousto_reference"=>56)
        );

         Recipe::unguard();
         foreach($data as $row){
           $row['created_at'] = \Carbon\Carbon::createFromFormat('d/m/Y H:i:s', $row['created_at'])->format('Y-m-d H:i:s');
           $row['updated_at'] = \Carbon\Carbon::createFromFormat('d/m/Y H:i:s', $row['updated_at'])->format('Y-m-d H:i:s');
           Recipe::create( $row );
         }
    }
}
